image : ubuntu

before_script:
 - apt-get update --yes
 - apt-get install --yes g++
 - apt-get install --yes cmake

all: 
    script:
        - mkdir build 
        - cd build 
        - cmake ..
        - make 
        - make test

