image : ubuntu

configure: 
    script:
        - mkdir build 
        - cd build 
        - cmake ..
       
build : 
    script:
        - cd build
        - make 
        
test:
    script:
        - cd build
        - make test

