image : ubuntu

before_script:
 - apt-get update --yes
 - apt-get install --yes g++
 - apt-get install --yes cmake

configure: 
    script:
        - mkdir build 
        - cd build 
        - cmake ..
       
build : 
    script:
        - mkdir build 
        - cd build
        - cmake ..
        - make 
        
test:
    script:
        - mkdir build 
        - cd build
        - cmake ..
        - make test

